### ISSUE TITLE
add a Dockerfile

### ISSUE THREAD

**Issue by ItsTarikBTW** [ccbikai/astro-aria#1]
Hello,

Firstly, thank you for your hard work on maintaining this project. It has been incredibly helpful for our development needs.

I would like to request the addition of a Dockerfile to this project to streamline the setup and deployment processes. A Dockerfile would enable users to quickly build and run the project in a consistent environment, regardless of the host operating system.

Details:

- Purpose: Simplify the setup and deployment process
- Environment: Docker
- Node.js Version: 20
- Package Manager: pnpm
- Suggested Features for Dockerfile:

1. Multi-stage build: To keep the final image lightweight.
2. Base image: Use Node.js 20 for the build stage and nginx

for the serve stage.

3. Steps:

        - Install pnpm globally.
        - Copy package.json and pnpm-lock.yaml to the container.
        - Install dependencies.
        - Copy the application code.
        - Build the project.
        - Serve the static files using Nginx.

Example Dockerfile:
```Dockerfile
# Stage 1: Build
FROM node:20 AS build

# Set working directory
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Copy package.json and pnpm-lock.yaml to the container
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy the rest of the application code to the container
COPY . .

# Build the Astro project
RUN pnpm run build

# Stage 2: Serve
FROM nginx:alpine AS serve

# Copy built static files from the build stage
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
```
Would it be possible to add a Dockerfile similar to the example provided above or modify it as needed to fit the project's specific requirements?

Thank you for considering this request. Your efforts in enhancing the usability of this project are greatly appreciated.

**Comment by ItsTarikBTW** [comment]
UPDATE:
I was traying to run  this project in Coolify ,
I added 3 files

1. /DockerfileDockerfile
```Dockerfile
FROM node:20-alpine AS base

FROM base AS deps

RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN yarn --frozen-lockfile;

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN yarn build

FROM nginx:alpine AS runner
COPY ./config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html

WORKDIR /usr/share/nginx/html

EXPOSE 80
```

2./.dockerignore
```Dockerfile
node_modules
```

3. /config/nginx/nginx.conf
```conf
worker_processes  1;

events {
  worker_connections  1024;
}

http {
  server {
    listen 80;
    server_name   _;

    root   /usr/share/nginx/html;
    index  index.html index.htm;
    include /etc/nginx/mime.types;

    gzip on;
    gzip_min_length 1000;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

    error_page 404 /404.html;
    location = /404.html {
            root /usr/share/nginx/html;
            internal;
    }

    location / {
            try_files $uri ${uri}.html $uri/index.html =404;
    }
  }
}
```
I hope that help someone :)

**Comment by ccbikai** [comment]
Thank you for your suggestion, I may not add a Dockerfile because deployment on different platforms varies.

This is a standard Astro project, and if you want to deploy it on various platforms, the best practice is to refer to Astro's deployment tutorial. https://docs.astro.build/en/guides/deploy/

If you have special needs, you can add them yourself after forking. Thank you very much for sharing your Dockerfile
